### ISSUE TITLE
Extension features stopped working except file creation

### ISSUE THREAD

**Issue by balazser** [predragnikolic/php-class-helper#2]
The extension creates a class in an empty .ts file but then does not add constructor, properties and the less anymore. Only the class creation feature is working me now. Did you experience the same issue?

**IDE Version:** VS Code Insiders
June 2018 (version 1.25)

**Extension version:**
[0.1.8]

**Comment by predragnikolic** [comment]
Yes, it doesn't work. 
I will see what's going on, as soon as I know I will keep you notified.

**Comment by predragnikolic** [comment]
Apparently the `location` property on the `SymbolInformation` is not there. 
Maybe they are changing the `SymbolInformation` interface. 
For now, I will wait until I am sure if they introduced a breaking change, or if this is just a bug at their side.

**Comment by joelday** [comment]
@predragnikolic https://github.com/Microsoft/vscode/issues/52874

**Comment by predragnikolic** [comment]
@joelday Thanks for the info :)

**Comment by joelday** [comment]
@predragnikolic Everything appears to be working except for ctrl-alt-c, although that could be user error on my part.

**Comment by predragnikolic** [comment]
@joelday `ctrl-alt-c` works for me. Maybe some other shortcut is overriding this one.
Type in the command pallet `Open Keyboard Shortcuts` and see if that is the case. 
If it is, than just reassign or remove the shortcut that you don't want  :)
